services:
  spring-boot:
    build: .
    ports:
      - target: 8080
        published: 8080
    networks:
      spring-net:
  postgres:
    image: "postgres:18.4-alpine"
    networks:
      spring-net:
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@@abdo@@"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    networks:
      spring-net:
    ports:
      - "6379:6379"

networks:
  spring-net:

volumes:
  postgres_data:
