--
-- PostgreSQL database dump
--

\restrict Qt9cRizUse1nf5iNMBLOL4RuZx5QMtJA0s4ebSF9QACVubbvPAOashJmhUQpwMJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses (
    address_id bigint NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    state character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    zipcode character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.addresses OWNER TO postgres;

--
-- Name: addresses_address_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    discount double precision,
    product_price double precision,
    quantity integer,
    cart_id bigint,
    product_id bigint
);


ALTER TABLE public.cart_items OWNER TO postgres;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts (
    cart_id bigint NOT NULL,
    total_price double precision,
    user_id bigint
);


ALTER TABLE public.carts OWNER TO postgres;

--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carts ALTER COLUMN cart_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    category_id bigint NOT NULL,
    category_name character varying(15) NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean,
    message character varying(255) NOT NULL,
    type character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['NEW_ORDER'::character varying, 'ORDER_CANCELLED'::character varying, 'RETURN_REQUESTED'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    order_item_id bigint NOT NULL,
    discount double precision NOT NULL,
    ordered_product_price double precision NOT NULL,
    quantity integer,
    order_id bigint,
    product_id bigint
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: order_items_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    order_date date,
    order_status character varying(255),
    total_amount double precision,
    address_id bigint,
    payment_id bigint,
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying, 'PAYMENT_FAILED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision,
    currency character varying(255),
    paid_at timestamp(6) without time zone,
    payment_intent_id character varying(255),
    payment_method character varying(255),
    provider character varying(255),
    status character varying(255),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    display_order integer,
    public_id character varying(255),
    url character varying(255),
    product_id bigint
);


ALTER TABLE public.product_images OWNER TO postgres;

--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    discount double precision NOT NULL,
    price double precision NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    special_price double precision,
    category_id bigint,
    seller_id bigint
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.products_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_seq OWNER TO postgres;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    role_name character varying(20),
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_SELLER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(120) NOT NULL,
    username character varying(20) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.addresses (address_id, city, country, state, street, zipcode, user_id) FROM stdin;
1	Meknès	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
2	Marjane	Morocco	50050	Meknes marjnae 2 N257	50050	1
3	Marjane 	Morocco	fes-meknes	Meknes marjnae 2 N257	50050	1
4	Marjane	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
5	Marjane 	Morocco	Fes-Meknes	Meknes marjnae 2 N257	50050	1
6	Marjane 	Morocco	Fes- Meknes	Meknes marjnae 2 N257	50050	1
7	Marjane 	Morocco	fes-meknes	Meknes marjnae 2 N257	50050	1
8	Marjane 	Morocco	Fes-Meknes	Meknes marjnae 2 N257	50050	1
9	Marjane	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
10	Marjane	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
11	Marjane	Morocco	fes-meknes	Meknes marjnae 2 N257	50050	1
12	Marjane	Morocco	Marjane 	Meknes marjnae 2 N257	50050	1
13	Marjane	Morocco	50050	Meknes marjnae 2 N257	50050	1
14	Marjane	Morocco	50050	Meknes marjnae 2 N257	50050	1
15	Marjane	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
16	Marjane	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
17	Marjane 2N257 , Meknès , Maroc	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
18	Marjane 2N257 , Meknès , Maroc	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
19	Meknès	Morocco	Fes-meknes	Meknes marjnae 2 N257	50050	1
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_items (id, discount, product_price, quantity, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carts (cart_id, total_price, user_id) FROM stdin;
1	0	1
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (category_id, category_name) FROM stdin;
1	Sports
2	Women
3	Electronics
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, is_read, message, type, user_id) FROM stdin;
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (order_item_id, discount, ordered_product_price, quantity, order_id, product_id) FROM stdin;
15	0	15	1	12	1
16	0	20	1	13	53
17	0	10	1	14	2
18	0	20	1	15	53
19	0	20	1	16	53
20	0	20	1	17	53
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, email, order_date, order_status, total_amount, address_id, payment_id) FROM stdin;
12	abdellahelghanami67@gmail.com	2026-08-08	PAID	15	12	12
13	abdellahelghanami67@gmail.com	2026-08-08	PAID	20	15	13
14	abdellahelghanami67@gmail.com	2026-08-08	PAID	10	16	14
15	abdellahelghanami67@gmail.com	2026-08-08	PAID	20	17	15
16	abdellahelghanami67@gmail.com	2026-08-08	PAID	20	18	16
17	abdellahelghanami67@gmail.com	2026-08-08	PAID	20	19	17
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payments (id, amount, currency, paid_at, payment_intent_id, payment_method, provider, status) FROM stdin;
1	25	usd	\N	pi_3U18od19TJ8v8Uba10ZExarI	\N	STRIPE	PENDING
2	25	usd	\N	pi_3U1E3T19TJ8v8Uba0uVl8WNo	\N	STRIPE	PENDING
3	25	usd	\N	pi_3U1T6819TJ8v8Uba0TchZGRH	\N	STRIPE	PENDING
4	15	usd	\N	pi_3U1TC019TJ8v8Uba0zWIPE3T	\N	STRIPE	PENDING
5	15	usd	\N	pi_3U1XHS19TJ8v8Uba1WY80Y1o	\N	STRIPE	PENDING
6	15	usd	\N	pi_3U1XJ019TJ8v8Uba0GsNTvEy	\N	STRIPE	PENDING
7	15	usd	\N	pi_3U1XZc19TJ8v8Uba0Dzj01lN	\N	STRIPE	PENDING
8	15	usd	\N	pi_3U1mFB19TJ8v8Uba0Tk8N5X3	\N	STRIPE	PENDING
9	15	usd	\N	pi_3U28gZ19TJ8v8Uba0gTnxCqm	\N	STRIPE	PENDING
10	15	usd	\N	pi_3U293219TJ8v8Uba1sc7Dtd4	\N	STRIPE	PENDING
11	15	usd	\N	pi_3U29Mr19TJ8v8Uba1LEEt6Rs	\N	STRIPE	PENDING
12	15	usd	2026-08-08 13:35:18.790555	pi_3U29T319TJ8v8Uba1JOJwFyW	\N	STRIPE	SUCCEEDED
13	20	usd	2026-08-08 17:02:26.917125	pi_3U2ChV19TJ8v8Uba0Au568uw	\N	STRIPE	SUCCEEDED
14	10	usd	2026-08-08 17:38:31.383611	pi_3U2DGK19TJ8v8Uba0yojLIRq	\N	STRIPE	SUCCEEDED
15	20	usd	2026-08-08 17:46:12.121724	pi_3U2DNq19TJ8v8Uba1J00Fu9D	\N	STRIPE	SUCCEEDED
16	20	usd	2026-08-08 17:57:34.23832	pi_3U2DYr19TJ8v8Uba0NuF4g92	\N	STRIPE	SUCCEEDED
17	20	usd	2026-08-08 18:21:29.201684	pi_3U2Dw019TJ8v8Uba0qwJhHve	\N	STRIPE	SUCCEEDED
\.


--
-- Data for Name: product_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_images (id, display_order, public_id, url, product_id) FROM stdin;
1	1	ll8zbww36lckamyuidw1	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1785951542/ll8zbww36lckamyuidw1.webp	1
2	1	v7ua1qrzkcibjou0b4ik	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1785951585/v7ua1qrzkcibjou0b4ik.avif	2
3	1	d0meo6geddzucgmuubzy	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786017237/d0meo6geddzucgmuubzy.webp	53
4	2	qohqq1ek63ow1gp6qcnb	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786017238/qohqq1ek63ow1gp6qcnb.webp	53
5	3	d2cnn6uxlkgvzwzbcwrf	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786017239/d2cnn6uxlkgvzwzbcwrf.webp	53
6	4	ofusypu7vg3zptpwbyk5	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786017240/ofusypu7vg3zptpwbyk5.webp	53
7	1	mhvn4jmonwkooseblh4f	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786218008/mhvn4jmonwkooseblh4f.png	103
8	2	gksaep0uinazw01dzlkh	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786218010/gksaep0uinazw01dzlkh.png	103
9	3	iidpcvzoyxityed07vkw	https://res.cloudinary.com/dcw6rqiaz/image/upload/v1786218011/iidpcvzoyxityed07vkw.jpg	103
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (product_id, description, discount, price, product_name, quantity, special_price, category_id, seller_id) FROM stdin;
1	Women sports shoe for running	0	15	Women sports shoe	0	15	2	1
2	Men Running shoes	0	10	Men Running shoes	0	10	1	1
53	Advanced hybrid ANC effectively blocks out surround noise for immersive listening. 	0	20	W820NB Plus Headphones	6	20	3	1
103	CPU : Snapdragon X Elite 4.3 GHz 12 cores RAM : 16 Go LPDDR5x Stockage : 512 Go SSD NVMe Gen4 NPU : Qualcomm® Hexagon™ (45 TOPS) GPU : Qualcomm Adreno GPU 128 	0	399	Microsoft Surface Laptop 7e Copilot+ PC Edition 15	10	399	3	1
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, role_name) FROM stdin;
1	ROLE_USER
2	ROLE_SELLER
3	ROLE_ADMIN
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_id, role_id) FROM stdin;
1	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, email, password, username) FROM stdin;
1	abdellahelghanami67@gmail.com	$2a$10$2FTN0SdnjM.OBNjEu5L3S.kpGhhFgkm56bDqI6lfDVCFcprsnJWPy	Abdellah0x1
\.


--
-- Name: addresses_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.addresses_address_id_seq', 19, true);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 9, true);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carts_cart_id_seq', 1, true);


--
-- Name: categories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_category_id_seq', 3, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- Name: order_items_order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_order_item_id_seq', 20, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 17, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payments_id_seq', 17, true);


--
-- Name: product_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_images_id_seq', 9, true);


--
-- Name: products_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_seq', 151, true);


--
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 3, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (address_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (cart_id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: products ukf55t6sm19p5lrihq24a6knota; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT ukf55t6sm19p5lrihq24a6knota UNIQUE (product_name);


--
-- Name: orders ukhaujdjk1ohmeixjhnhslchrp1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukhaujdjk1ohmeixjhnhslchrp1 UNIQUE (payment_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: orders fk8aol9f99s97mtyhij0tvfj41f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk8aol9f99s97mtyhij0tvfj41f FOREIGN KEY (payment_id) REFERENCES public.payments(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: products fkbgw3lyxhsml3kfqnfr45o0vbj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkbgw3lyxhsml3kfqnfr45o0vbj FOREIGN KEY (seller_id) REFERENCES public.users(user_id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: orders fkhlglkvf5i60dv6dn397ethgpt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkhlglkvf5i60dv6dn397ethgpt FOREIGN KEY (address_id) REFERENCES public.addresses(address_id);


--
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(category_id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(cart_id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- PostgreSQL database dump complete
--

\unrestrict Qt9cRizUse1nf5iNMBLOL4RuZx5QMtJA0s4ebSF9QACVubbvPAOashJmhUQpwMJ

