spring.application.name=sb-ecom
spring.h2.console.enabled=true

#database config
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=@@abdo@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
project.image=images/

#set log levels
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG


#jwt related variables
spring.app.jwtSecret=gk7D2pEBeq2HOBj48ImHaNdPELcb9XvXPtCvDligtKh
spring.app.jwtExpirationMs=3000000

spring.app.jwtCookie=buyFlowJWT

#cloudinary stuff
spring.app.cloudinary.api-key=183291723212937
spring.app.cloudinary.api-secret=SH7KB9CTXCiF24hpASZVU3cmyvw
spring.app.cloudinary.cloud-name=dcw6rqiaz
