spring.application.name=sb-ecom
spring.h2.console.enabled=true

#database config
spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
project.image=images/

#set log levels
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG


#jwt related variables
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

spring.app.jwtCookie=${JWT_COOKIE}

#cloudinary stuff
spring.app.cloudinary.api-key=${CLOUDINARY_KEY}
spring.app.cloudinary.api-secret=${CLOUDINARY_SECRET}
spring.app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

#stripe
spring.stripe.secret-key=${STRIPE_SECRET_KEY}
spring.stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}


#redis
spring.data.redis.host=redis
spring.data.redis.port=6379



#email and smtp
spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false


