spring.application.name=sb-ecom
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
project.image=images/

#set log levels
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG


#jwt related variables
spring.app.jwtSecret=gk7D2pEBeq2HOBj48ImHaNdPELcb9XvXPtCvDligtKh
spring.app.jwtExpirationMs=3000000

spring.app.jwtCookie=buyFlowJWT